### PR TITLE
Synch up dev and prod

### PR DESCRIPTION
**Pull request by micheal-w-wells**
All PR's by last team since last prod deploy, mostly tests, load testing config, some stuff related to animal observations in web and API, metabase config, and lastly the securesite cookie fix.

### CODE REVIEW

**Comment by micheal-w-wells** [comment]
@rstens going on a limb and assuming this won't deploy to prod by just me opening it.

**Comment by rstens** [comment]
It will create a PR, but build is failing.

https://console.pathfinder.gov.bc.ca:8443/console/project/8ecbmv-tools/browse/pods/invasivesbc-api-build-787-30-build?tab=logs

```

npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
--
  | npm ERR!
  | npm ERR!
  | npm ERR! Missing: gulp-sourcemaps@latest
  | npm ERR!
  |  
  | npm ERR! A complete log of this run can be found in:
  | npm ERR!     /opt/app-root/src/app/.npm/_logs/2020-08-18T23_52_20_708Z-debug.log
  | Removing intermediate container 8254f8b3282b
  | error: build error: The command '/bin/sh -c npm ci' returned a non-zero code: 1


```

**Comment by rstens** [comment]
> It will create a PR, but build is failing.
> 
> https://console.pathfinder.gov.bc.ca:8443/console/project/8ecbmv-tools/browse/pods/invasivesbc-api-build-787-30-build?tab=logs
> 
> ```
> 
> npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
> --
>   | npm ERR!
>   | npm ERR!
>   | npm ERR! Missing: gulp-sourcemaps@latest
>   | npm ERR!
>   |  
>   | npm ERR! A complete log of this run can be found in:
>   | npm ERR!     /opt/app-root/src/app/.npm/_logs/2020-08-18T23_52_20_708Z-debug.log
>   | Removing intermediate container 8254f8b3282b
>   | error: build error: The command '/bin/sh -c npm ci' returned a non-zero code: 1
> ```

This has now been resolved. It was a successful build.

**Review by rstens — APPROVED** [review]
Looks like it worked so far. After reviewing the pipeline code for the prod submission, I believe we can go forward.

**Pull request merged**
